# Generated by Django 5.0.2 on 2024-02-28 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover_image',
            field=models.ImageField(blank=True, upload_to='static/images/'),
        ),
    ]
